version: '3'

networks:
  app-tier:
    driver: bridge

services:
  cassandra:
    image: cassandra:3
    networks:
      - app-tier
    ports:
      - 9042:9042
  kong:
    image: kong
    networks:
      - app-tier
    links:
      - cassandra
    env_file:
      - env/kong.env
    volumes:
      - ./bin:/data/bin
    ports:
      - 8001:8001
      - 8000:8000
    command: sh /data/bin/start-kong.sh
  kafka:
    image: spotify/kafkaproxy
    networks:
      - app-tier
    ports:
      - 9092:9092
      - 2181:2181
    env_file:
      - env/kafka.env
  hadoop-namenode:
    image: uhopper/hadoop-namenode
    networks:
      - app-tier
    env_file:
      - env/hadoop-namenode.env
  hadoop-datanode:
    image: uhopper/hadoop-datanode
    networks:
      - app-tier
    env_file:
      - env/hadoop-datanode.env
    links:
      - hadoop-namenode
  hadoop-resourcemanager:
    image: uhopper/hadoop-resourcemanager
    networks:
      - app-tier
    env_file:
      - env/hadoop-resourcemanager.env
    links:
      - hadoop-namenode
  hadoop-nodemanager:
    image: uhopper/hadoop-nodemanager
    networks:
      - app-tier
    env_file:
      - env/hadoop-nodemanager.env
    links:
      - hadoop-namenode
      - hadoop-resourcemanager
  app:
    image: openjdk:11-jdk-slim
    networks:
      - app-tier
    volumes:
      - ./assembly:/opt/assembly
    command: javac -version
