version: '3'

networks:
  app-tier:
    driver: bridge

services:
  cassandra:
    image: cassandra:3
    networks:
      - app-tier
    ports:
      - 9042:9042
  kong:
    image: kong
    networks:
      - app-tier
    links:
      - cassandra
    env_file:
      - env/kong.env
    volumes:
      - ./bin:/data/bin
    ports:
      - 8001:8001
      - 8000:8000
    command: sh /data/bin/start-kong.sh
  kafka:
    image: spotify/kafkaproxy
    networks:
      - app-tier
    ports:
      - 9092:9092
      - 2181:2181
    env_file:
      - env/kafka.env
  app:
    image: openjdk:11-jdk-slim
    networks:
      - app-tier
    volumes:
      - ./assembly:/opt/assembly
    command: javac -version
